# Specify the base image
image: debian:latest

# Define the stages of the pipeline
stages:
  - build
  - test
  - quality

# Define jobs in each stage
build:
  stage: build
  script:
    - cd ./src/main/java/com/paradise
    - javac Main.java

test:
  stage: test
  script:
    - cd ./src/test/java/com/paradise
    - java -cp . Test.java
